### ISSUE TITLE
TransformMob, FloatChat and Boat

### ISSUE THREAD

**Issue by flaxues** [EndKingdom/Some-of-TheEnderCreeper0s-Plugins-AKA-Matthew4444s-Plugins-#3]
@matthew4444 Could i put these plugins in ur repo
http://www.mediafire.com/download/fayu8il2ad1th4a/TransformMob_v0.1.phar
http://www.mediafire.com/download/bze633oqomlpn9h/phar_Boat-1.0_DktRUjTyAQ0SeHO.phar
http://www.mediafire.com/download/12k08oreisr1eem/FloatChat_v0_1_0.phar

**Comment by matthew4444** [comment]
Ok

**Comment by matthew4444** [comment]
http://www.mediafire.com/download/fayu8il2ad1th4a/TransformMob_v0.1.phar

**Comment by flaxues** [comment]
Floatchat and Boat too :)

**Comment by matthew4444** [comment]
Ok

**Comment by matthew4444** [comment]
Ok

**Comment by matthew4444** [comment]
http://www.mediafire.com/download/bze633oqomlpn9h/phar_Boat-1.0_DktRUjTyAQ0SeHO.phar
http://www.mediafire.com/download/12k08oreisr1eem/FloatChat_v0_1_0.phar

**Comment by matthew4444** [comment]
Hey i gtg
Its 6 34 pm est 
Ill be on tommorow at somewhere around 9-11 pm est,or somonrwherr after 10 am est but before 5 am est

**Comment by EndKingdom-Owner** [comment]
Hi guys you want to make simonsays minigame or buildbattle minigame because Edward is working on EnderAuth

**Comment by matthew4444** [comment]
Ya,both plz

**Comment by matthew4444** [comment]
hey can someone put these plugins in my repo plz.
http://www.mediafire.com/?lqn4voq2ldfji

**Comment by EndKingdom-Owner** [comment]
We need to work on the auth now

**Comment by matthew4444** [comment]
Hey I'm back
